# Site wide configuration

title: Paint by Number
locale: en_US
description: Data Visualization from Lê and Lê
logo:
search: true
baseurl: ""
url: http://paint-by-number.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Anh Le
  avatar: bio-anhle.jpg
  email: anh.le91@gmail.com
  disqus-shortname: paint-by-number
  twitter: #username
  facebook: #username
  github: paint-by-number
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-42749331-3
    verify: jpb13Uu0p1-ASxwY10_AOuRIS-ohYmYld1Urj0RQuns
    ad-client:
    ad-slot: 
  bing-verify:
